// ISO 3166-1 alpha-2 country codes with names
export const COUNTRIES = [
  { code: 'SE', name: 'Sweden', dial_code: '+46' },
  { code: 'NO', name: 'Norway', dial_code: '+47' },
  { code: 'DK', name: 'Denmark', dial_code: '+45' },
  { code: 'FI', name: 'Finland', dial_code: '+358' },
  { code: 'IS', name: 'Iceland', dial_code: '+354' },
  { code: 'AT', name: 'Austria', dial_code: '+43' },
  { code: 'BE', name: 'Belgium', dial_code: '+32' },
  { code: 'BG', name: 'Bulgaria', dial_code: '+359' },
  { code: 'HR', name: 'Croatia', dial_code: '+385' },
  { code: 'CY', name: 'Cyprus', dial_code: '+357' },
  { code: 'CZ', name: 'Czech Republic', dial_code: '+420' },
  { code: 'EE', name: 'Estonia', dial_code: '+372' },
  { code: 'FR', name: 'France', dial_code: '+33' },
  { code: 'DE', name: 'Germany', dial_code: '+49' },
  { code: 'GR', name: 'Greece', dial_code: '+30' },
  { code: 'HU', name: 'Hungary', dial_code: '+36' },
  { code: 'IE', name: 'Ireland', dial_code: '+353' },
  { code: 'IT', name: 'Italy', dial_code: '+39' },
  { code: 'LV', name: 'Latvia', dial_code: '+371' },
  { code: 'LT', name: 'Lithuania', dial_code: '+370' },
  { code: 'LU', name: 'Luxembourg', dial_code: '+352' },
  { code: 'MT', name: 'Malta', dial_code: '+356' },
  { code: 'NL', name: 'Netherlands', dial_code: '+31' },
  { code: 'PL', name: 'Poland', dial_code: '+48' },
  { code: 'PT', name: 'Portugal', dial_code: '+351' },
  { code: 'RO', name: 'Romania', dial_code: '+40' },
  { code: 'SK', name: 'Slovakia', dial_code: '+421' },
  { code: 'SI', name: 'Slovenia', dial_code: '+386' },
  { code: 'ES', name: 'Spain', dial_code: '+34' },
  { code: 'GB', name: 'United Kingdom', dial_code: '+44' },
  { code: 'CH', name: 'Switzerland', dial_code: '+41' },
  { code: 'US', name: 'United States', dial_code: '+1' },
  { code: 'CA', name: 'Canada', dial_code: '+1' },
  { code: 'AU', name: 'Australia', dial_code: '+61' },
  { code: 'NZ', name: 'New Zealand', dial_code: '+64' },
  { code: 'JP', name: 'Japan', dial_code: '+81' },
  { code: 'CN', name: 'China', dial_code: '+86' },
  { code: 'IN', name: 'India', dial_code: '+91' },
  { code: 'BR', name: 'Brazil', dial_code: '+55' },
  { code: 'MX', name: 'Mexico', dial_code: '+52' },
  { code: 'AR', name: 'Argentina', dial_code: '+54' },
  { code: 'CL', name: 'Chile', dial_code: '+56' },
  { code: 'CO', name: 'Colombia', dial_code: '+57' },
  { code: 'PE', name: 'Peru', dial_code: '+51' },
  { code: 'ZA', name: 'South Africa', dial_code: '+27' },
  { code: 'EG', name: 'Egypt', dial_code: '+20' },
  { code: 'AE', name: 'United Arab Emirates', dial_code: '+971' },
  { code: 'SA', name: 'Saudi Arabia', dial_code: '+966' },
  { code: 'TR', name: 'Turkey', dial_code: '+90' },
  { code: 'RU', name: 'Russia', dial_code: '+7' },
  { code: 'KR', name: 'South Korea', dial_code: '+82' },
  { code: 'SG', name: 'Singapore', dial_code: '+65' },
  { code: 'MY', name: 'Malaysia', dial_code: '+60' },
  { code: 'TH', name: 'Thailand', dial_code: '+66' },
  { code: 'ID', name: 'Indonesia', dial_code: '+62' },
  { code: 'PH', name: 'Philippines', dial_code: '+63' },
  { code: 'VN', name: 'Vietnam', dial_code: '+84' },
  { code: 'HK', name: 'Hong Kong', dial_code: '+852' },
  { code: 'TW', name: 'Taiwan', dial_code: '+886' },
  { code: 'IL', name: 'Israel', dial_code: '+972' },
].sort((a, b) => a.name.localeCompare(b.name)); // Sort alphabetically by name

